### DISCUSSION TITLE
[Question] How can an individual layer be merged from model into another?

### DISCUSSION THREAD

**Discussion by T145** [arcee-ai/mergekit#476] [Q&A]
I made the following configuration:
```
base_model: T145/ZEUS-8B-V10
dtype: bfloat16
merge_method: linear
parameters:
  int8_mask: 1.0
  normalize: 1.0
  weight:
  - filter: lm_head
    value: 0.0
  - value: 1.0
slices:
- sources:
  - layer_range: [0, 32]
    model: SicariusSicariiStuff/LLAMA-3_8B_Unaligned_BETA
    parameters:
      weight:
      - filter: lm_head
        value: 1.0
      - value: 0.0
  - layer_range: [0, 32]
    model: T145/ZEUS-8B-V10
tokenizer_source: base
```
However after running benchmarks, the result performed significantly worse than the base model. To my understanding this config should preserve the `lm_head` from the target model and everything else from the base model. Is there something wrong I did here, or are drastic changes to be expected?
