### ISSUE TITLE
About mergekit behavior by tokenizer

### ISSUE THREAD

**Issue by tomgm777** [arcee-ai/mergekit#169]
Hello.
I used mergekit to merge various models, but in the case below, the merge process completes normally without any errors, but when I play it back with text-generation-webui, it outputs an incomprehensible answer.

https://huggingface.co/cyberagent/calm2-7b (tokenizer.json use)
https://huggingface.co/TheTravellingEngineer/llama2-7b-chat-hf-dpo (tokenizer.model use)

Below is my yaml.

```
models:
  - model: models/calm2-7b
    # no parameters necessary for base model
  - model: models/llama2-7b-chat-hf-dpo # follow user intent
    parameters:
      density: 1
      weight: 0.4
merge_method: dare_ties
base_model: models/calm2-7b
parameters:
  normalize: true
  int8_mask: true
dtype: bfloat16
tokenizer_source: base
```

command option
--cuda --allow-crimes --trust-remote-code

I tried it with other models, but this problem occurs when the base model is a model that uses tokenizer.json and the model to be merged uses only tokenizer.model.
Also,
tokenizer_source: union
If I specify , mergekit processing seems to freeze.

Do you know of any countermeasures regarding this matter?
