### ISSUE TITLE
Model download issue

### ISSUE THREAD

**Issue by yingxin-chen** [arcee-ai/mergekit#194]
I want to use MergeKit to merge models, but I can't download the models from Hugging Face due to network issues. 

Can MergeKit use models that have already been downloaded locally?

**Comment by cg123** [comment]
Absolutely! You can use an absolute path to a model on disk in place of a Hugging Face repo name.

For example, something like this:
```yaml
merge_method: linear
models:
  - model: /workspace/model_a
  - model: /workspace/model_b
```
