### ISSUE TITLE
Different parameter sizes shrinks

### ISSUE THREAD

**Issue by Katehuuh** [arcee-ai/mergekit#208]
hoi, Similar to #154 #100 I was figure out how to make more advance config, all used model are already merged:
```yaml
slices:
  - sources:
      - model: ./model-1-7B
        layer_range: [0, 32]
          parameters:
            density: 0.5
            weight: 1.0
      - model: ./model-2-20B
        layer_range: [23, 62]
          parameters:
            density: 0.33
            weight: 0.7
      - model: ./model-3-11B
        layer_range: [0, 40]
          parameters:
            density: 0.25
            weight: 0.5
merge_method: dare_ties
base_model: ./model-0-13B
dtype: float16
```
20B is frankenmerging so theoriquelly no need to prune #24?
I would appreciate any config that could merge 7B [32], 11B [48], 20B [62] back to 13B [40], all [layer] base of model HF info.

Edit: I've modify [gradient-slerp.yml](https://github.com/arcee-ai/mergekit/blob/main/examples/gradient-slerp.yml):
```yaml
slices:
  - sources:
      - model: ./model-1-7B
        layer_range: [0, 32]
      - model: ./model-3-11B
        layer_range: [0, 32]
merge_method: slerp
base_model: ./model-1-7B
parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1]
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - value: 0.5
dtype: float16
```
Output Is _ok_, reasoning but high hallucination.
