### ISSUE TITLE
What does `#no parameters necessary for base model`

### ISSUE THREAD

**Issue by NeonBohdan** [arcee-ai/mergekit#230]
Everyone is using 
`#no parameters necessary for base model` in their merges

```
models:
  - model: mistralai/Mistral-7B-Instruct-v0.2
    #no parameters necessary for base model
  - model: mistralai/Mistral-7B-v0.1+predibase/customer_support
    parameters:
      density: 0.5
      weight: 0.5
  - model: NousResearch/Nous-Hermes-2-Mistral-7B-DPO
    parameters:
      density: 0.5
      weight: 0.5

merge_method: ties
base_model: mistralai/Mistral-7B-Instruct-v0.2
parameters:
  normalize: false
  int8_mask: true
dtype: float16
```

But in this merge
What is the parameters auto-set in place of this phrase 
And what is the difference with removing base model from the list of three
