### ISSUE TITLE
Sign consensus don't return `all True mask`

### ISSUE THREAD

**Issue by NeonBohdan** [arcee-ai/mergekit#231]
I desided to debug next merge yaml

Clearly it skips `sparsify` and scales down task vector with 0.75 weight

But it also does `sign consensus`. On only one task vector it should be `all True` simply

Instead some prescentage of them are False
bfloat16: 7%
float32: 1e-6%

Even float32 can't manage to do `all True`

Can this code that is responsible for this been updated to have higher accuracy
https://github.com/arcee-ai/mergekit/blob/9a541798231dc4c1e088caf271b04474685e4dcb/mergekit/merge_methods/generalized_task_arithmetic.py#L196 

```
models:
  - model: mlabonne/NeuralHermes-2.5-Mistral-7B
    parameters:
      density: 1.0
      weight: 0.75
merge_method: dare_ties
base_model: mistralai/Mistral-7B-v0.1
dtype: float32
```
