### ISSUE TITLE
ChatVector

### ISSUE THREAD

**Issue by tomgm777** [arcee-ai/mergekit#248]
mergekit is a great tool that allows me to merge 70B models even with 64G memory.

https://huggingface.co/aixsatoshi/Swallow-MX-8x7b-NVE-chatvector-Mixtral-instruct-v2

Is it possible to configure a merge like the above method (ChatVector)?
Doing this directly with Python is possible for about 7B, but the 70B model ran out of memory.

**Comment by cg123** [comment]
You can do this wit the `task_arithmetic` merge method. Here's a config that is equivalent to what they did:

```yml
merge_method: task_arithmetic
base_model: mistralai/Mixtral-8x7B-v0.1
models:
   - model: tokyotech-llm/Swallow-MX-8x7b-NVE-v0.1
     parameters:
     weight: 1.0
   - model: mistralai/Mixtral-8x7B-Instruct-v0.1
     parameters:
     weight: 0.8
dtype: bfloat16
```

That will give you Mixtral-8x7B-v0.1 + 1.0 * (Swallow-MX-8x7b-NVE-v0.1 - Mixtral-8x7B-v0.1) + 0.8*(Mixtral-8x7B-Instruct-v0.1 - Mixtral-8x7B-v0.1), which if you do some rearranging is the same thing.

Hope this helps!

**Comment by tomgm777** [comment]
thank you
When I try the following settings, I get the following error.

```
merge_method: task_arithmetic
base_model: E:/models/Llama-2-70b-hf
models:
   - model: E:/models/karakuri-lm-70b-v0.1
     parameters:
     weight: 1.0
   - model: F:/models/Midnight-Rose-70B-v2.0.3
     parameters:
     weight: 0.8
dtype: bfloat16
tokenizer_source: base

```
RuntimeError: Missing required parameter weight for E:/models/karakuri-lm-70b-v0.1.model.layers.0.input_layernorm.weight

This is due to the difference in VOCAB SIZE, so in PY it was done as follows. Is there a way to reflect this skip processing?

```
from transformers import AutoModelForCausalLM
import torch

base_model = AutoModelForCausalLM.from_pretrained(
    "E:/models/Llama-2-70b-hf",
    torch_dtype=torch.bfloat16,
    device_map="cpu",
)

inst_model = AutoModelForCausalLM.from_pretrained(
    "F:/models/Midnight-Rose-70B-v2.0.3",
    torch_dtype=torch.bfloat16,
    device_map="cpu",
)

cp_model = AutoModelForCausalLM.from_pretrained(
    "E:/models/karakuri-lm-70b-v0.1",
    torch_dtype=torch.bfloat16,
    device_map="cpu",
)

# this skip
skip_layers = ["model.embed_tokens.weight", "lm_head.weight"]

for k, v in cp_model.state_dict().items():
# this skip
    if (k in skip_layers) or ("layernorm" in k):
        continue

    chat_vector = inst_model.state_dict()[k] - base_model.state_dict()[k]
    new_v = v + ( 0.8 * chat_vector.to(v.device) )
    v.copy_(new_v)

cp_model.save_pretrained("G:/merge/Karakuri-CV")

```
