### ISSUE TITLE
Request for scripts to reproduce the results in the Mergekits paper

### ISSUE THREAD

**Issue by VimaGupta345** [arcee-ai/mergekit#261]
Thanks a lot for this amazing work! It has been so much fun working with mergekits repo and creating new and cool models. 

Could you please share the scripts to reproduce the results as described in the paper? I am curious to know the yaml parameters used for the results. 

Thank you!

**Comment by metric-space** [comment]
```yaml
models:
  - model: meta-llama/Llama-2-7b-hf
    #no parameters necessary for base model
  - model: meta-llama/Llama-2-7b-chat-hf
    parameters:
      density: 0.5
      weight: 0.5
  - model: epfl-llm/meditron-7b
    parameters:
      density: 0.5
      weight: 0.5
merge_method: dare_ties
base_model: meta-llama/Llama-2-7b-hf
parameters:
  normalize: false
  int8_mask: true
dtype: float16
```

```yaml
models:
  - model: /dev/shm/cleaned_meditron
    parameters:
      weight: 0.7
  - model: meta-llama/Llama-2-7b-chat-hf
    parameters:
      weight: 0.3
merge_method: linear
dtype: float16

```

```yaml
models:
  - model: meta-llama/Llama-2-7b-hf
    #no parameters necessary for base model
  - model: meta-llama/Llama-2-7b-chat-hf
    parameters:
      density: 0.8
      weight: 0.5
  - model: epfl-llm/meditron-7b
    parameters:
      density: 0.8
      weight: 0.5
merge_method: ties
base_model: meta-llama/Llama-2-7b-hf
parameters:
  normalize: false
  int8_mask: true
dtype: float16
```

```yaml

models:
  - model: meta-llama/Llama-2-7b-chat-hf
  - model: epfl-llm/meditron-7b
merge_method: slerp
base_model: meta-llama/Llama-2-7b-chat-hf
parameters:
    t:
    - value: 0.5
dtype: float16
```

```bash
MODEL=$1

PYTHONPATH=$PYTHONPATH: time python lm_eval --model hf --model_args pretrained="$MODEL" --tasks medmcqa,usmle --batch_size "auto"
PYTHONPATH=$PYTHONPATH: time python lm_eval --model hf --model_args pretrained="$MODEL" --tasks pubmedqa --batch_size "auto"  --all_splits
PYTHONPATH=$PYTHONPATH: time python lm_eval --model hf --model_args pretrained="$MODEL" --tasks arc_challenge,hellaswag,mmlu --batch_size "auto
```
