### ISSUE TITLE
Merge only the transformer parts (including the input embedding layer)

### ISSUE THREAD

**Issue by hank0316** [arcee-ai/mergekit#308]
Hi,

I want to know how to merge the transformer layers and input embedding layer only. I want to keep the original `lm_head`. Is this possible?

**Comment by Vincent-Li-9701** [comment]
If you are using a huggingface ckpt and this is a lm model this might not be possible. The reason behind is that the embedding layer IS the lm_head. You can check out this post https://discuss.huggingface.co/t/why-is-the-lm-head-layer-in-gpt2lmheadmodel-not-a-parameter/639.

**Comment by cg123** [comment]
Yes, this is possible! You can do so like this, for example:

```yml
merge_method: linear
models:
  - model: model_a
    parameters:
      weight: 1
  - model: model_b
    parameters:
      weight:
        - filter: lm_head
          value: 0
        - value: 1
```
That sets `weight` to 0 for `model_b.lm_head`, so the result will have `lm_head` identical to `model_a`'s. 

If you're using a merge method that doesn't have an easy way to do this using parameters, you can also use a bit of a cheesy hack with the slicing functionality. When using the `slices:` config syntax `lm_head` will be taken from the last slice, so you can add a zero-length slice on the end that only includes your original model - like so:

```yml
slices:
  - sources:
      - model: model_a
        layer_range: [0, 32]
      - model: model_b
        layer_range: [0, 32]
  - sources:
      - model: model_a
        layer_range: [32, 32] # zero length
```
