### ISSUE TITLE
how to merge for different rope scaling?

### ISSUE THREAD

**Issue by sangmandu** [arcee-ai/mergekit#325]
it's good just to merge?

- basemodel rope : 500,000
- model1 rope : 500,000
- model2 rope : 20,000,000

how can I do?

**Comment by sangmandu** [comment]
I just changed the rope of basemodel and model1 before merging but not working well it seems

**Comment by jukofyork** [comment]
> I just changed the rope scailing of basemodel and model1 before merging but not working well it seems especially, I used merge-evolve. Is there a no consideration about [rope](https://github.com/vllm-project/vllm/pull/555) when using merge-evlove right?

Sadly, you can't change it like this as it's just 2 parameters that generate the whole thing programmatically.

**Comment by cg123** [comment]
Models with different RoPE Theta values can be quite difficult to merge, when it's even possible. This is a function of how much extended pretraining was done at the new context length. If it was a relatively light train, like kaiokendev's original extended context Llama 1 models, then merging kind of just works. With recent models I've seen some people have some success with very, very low weight merges but haven't had much luck myself. 

The one pattern that I do see *fairly* consistently work is adding the difference between an extended-context model and the base to a recipe, like this:
```yml
merge_method: task_arithmetic
base_model: the_base_model
models:
  - model: the_base_model_but_200k
    parameters:
      weight: 1.0
# and then only non-extended context models
  - model: other_stuff
    parameters:
      weight: 0.3
... etc
```
