### ISSUE TITLE
Why all inputs to a slice must contain the same number of layers?

### ISSUE THREAD

**Issue by Mihaiii** [arcee-ai/mergekit#354]
I was doing some passthrough magic and [got hit by this error](https://github.com/arcee-ai/mergekit/blob/5b09c8e889480d5732cc476f3e836d125297eccd/mergekit/plan.py#L226).

I must admit I'm a little confused by it and it looks like a regression to me. [I used passthrough for eliminating layers in February this year](https://huggingface.co/Mihaiii/Cluj-Napoca-0.2) - before the PR that contained that assert line was merged - and everything was ok. I'm also trying to understand the code better.

Why all inputs to a slice must contain the same number of layers and did it indeed work without this restriction before (i.e., is the code more rigid now)?

Update: here is the config I used:

```yml
slices:
  - sources:
    - model: Mihaiii/Venusaur
      layer_range: [0, 1]
    - model: Mihaiii/Venusaur
      layer_range: [0, 2]
    - model: Mihaiii/Venusaur
      layer_range: [1, 2]
merge_method: passthrough
dtype: float32
```

**Comment by Mihaiii** [comment]
Nevermind, my config was wrong. Here is the correct one:

```yml
slices:
  - sources:
    - model: Mihaiii/Venusaur
      layer_range: [0, 1]
  - sources:
    - model: Mihaiii/Venusaur
      layer_range: [0, 2]
  - sources:
    - model: Mihaiii/Venusaur
      layer_range: [1, 2]
merge_method: passthrough
dtype: float32
```
