### ISSUE TITLE
Questions about Config

### ISSUE THREAD

**Issue by Zheng-Jay** [arcee-ai/mergekit#378]
Thank you for your outstanding contribution! 
I am not very familiar with the configuration of model fusion, and I couldn't find explanations for each parameter in the repository. I encountered some issues. Here is an example:
```
slices:
  - sources:
      - model: psmathur/orca_mini_v3_13b
        layer_range: [0, 40]
      - model: garage-bAInd/Platypus2-13B
        layer_range: [0, 40]
# or, the equivalent models: syntax:
# models:
#   - model: psmathur/orca_mini_v3_13b
#   - model: garage-bAInd/Platypus2-13B
merge_method: slerp
base_model: psmathur/orca_mini_v3_13b
parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1]
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - value: 0.5 # fallback for rest of tensors
dtype: float16
```
1、The values [0, 0.5, 0.3, 0.7, 1] represent the weights for different layers, but to which of the two models do they refer?
2、For other parameters, in this example, they are set to 0.5 (value: 0.5). If I want to set the base model to 0.3 and the other model to 0.7, how should I modify it?
3、I found that some configuration files have `density`. What does it represent? How is it different from `weight`?
