### ISSUE TITLE
Issue with mistral v03 based models using union tokenizer source

### ISSUE THREAD

**Issue by guillermo-gabrielli-fer** [arcee-ai/mergekit#394]
### Environment 
Conda environment:
python=3.10
mergekit commit f086664c983ad8b5f126d40ce2e4385f9e65f32c (latest)
transformers from git @ git+https://github.com/huggingface/transformers.git@85817d98fb60977c97e3014196a462b732d2ed1a (latest)

Same issue with the transformers version installed by mergekit, I think it's 4.44

### Issue

When merging two models based on mistral v03 base, at saving the base tokenizer to avoid mutating it, it fails to load it back.

configuration file (these were not the original models but they reproduce the issue):
```
models:
  - model: mistralai/Mistral-7B-v0.3
  - model: mistralai/Mistral-7B-Instruct-v0.3
merge_method: slerp
base_model: mistralai/Mistral-7B-v0.3
tokenizer:
  source: union
parameters:
  t:
    - value: 0.8
dtype: bfloat16
```

Exception:
```
mergekit/mergekit/tokenizer/build.py", line 155, in build_union_tokenizer
    res = transformers.AutoTokenizer.from_pretrained(
[......]
transformers/models/llama/tokenization_llama.py", line 201, in get_spm_processor
    with open(self.vocab_file, "rb") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
(this is the code with the comment:  # HACK: save base tokenizer to temp dir and reload to avoid mutating base_tok)

I could get past that error by saving also as legacy_format=True, but then it shows:
```
mergekit/mergekit/tokenizer/embed.py", line 62, in execute
    token_configs = dict(**self.tokens) or {}
TypeError: dict() argument after ** must be a mapping, not NoneType
```
I could get the merge to finish by moving the {} fallback inside the dict, but I'm not sure yet if the result is correct.

[tracebacks.txt](https://github.com/user-attachments/files/16564045/tracebacks.txt)

[pip_freeze.txt](https://github.com/user-attachments/files/16564042/pip_freeze.txt)
