### ISSUE TITLE
Example of a config file for task_arithmetic 'negative' operation and a case for 'Task analogies'

### ISSUE THREAD

**Issue by eunbin079** [arcee-ai/mergekit#400]
In the [README](https://github.com/arcee-ai/mergekit?tab=readme-ov-file#merge-methods), the Task Arithmetic paper describes two methods:

**1. Applying a negative operation to the model weights to mitigate a specific behavior. 
2. Using task analogy (Task Vector D ≈ Task Vector C + (Task Vector B − Task Vector A)).**
Could I find examples for these?

### Negative Operation
- base model 'A' and a fine-tuned model 'a'.
- 'model A' and 'model a' have the same model architecture.
- how can I write the details for the 'negative' operation in the below config.
- negative.yml
```yml
models:
  - model: A
  - model: a
merge_method: task_arithmetic
base_model: A
dtype: float16
```

### Task Analogy
- base model A, a fine-tuned model a(from base model A), and a base model B.
- I want to obtain a fine-tuned model b (= B + (a − A)) using the task vector (a − A).
- The relationship between A and a is similar to the relationship between B and b.
- Do I need to create the 'a-A' task vector myself, or is it generated within MergeKit?
- How should I represent the 'a-A' task vector in the config?
- How can the above be reflected in the YAML file?
- analogy.yml
```yml
models:
  - model: B
  - model: ??
merge_method: task_arithmetic
base_model: B 
dtype: float16
```

please help me!!
