### ISSUE TITLE
Qwen2.5 14B models are ... sometimes? ... having their token vocabulary truncated down to 'actual'?

### ISSUE THREAD

**Issue by ann-brown** [arcee-ai/mergekit#425]
Actual example of a merge that produced this issue:

```
models:
  - model: Qwen/Qwen2.5-14B-Instruct
    parameters:
      weight: 0.3
      density: 0.4
merge_method: della
base_model: Lambent/qwen2.5-lumen-rebased-14B
parameters:
  epsilon: 0.05
  lambda: 1
dtype: bfloat16
tokenizer_source: base
```

Possibly relevant step prior is that the base_model extracted a LORA using `mergekit-extract-lora v000000/Qwen2.5-Lumen-14B Qwen/Qwen2.5-14B-Instruct OUTPUT_PATH --rank=128`, but applying that did not in itself change the vocab_size or embedding layer on applying.

Additional relevant information is that if I get the tokenizer vocab size with `tokenizer_vocab_size = len(tokenizer)` from ... any Qwen 2.5 14B model, I get the `151665` number rather than the `152064` number that's in the config.json.

I don't fully understand why it's trimming the vocabulary size and embedding layer down in this merge method but none of the others, but it's annoying for compatibility and specifying the tokenizer_source doesn't seem to address the issue (presumably because the tokenizer doesn't actually have 152064 worth of vocabulary)
