### ISSUE TITLE
Report issues regarding the architecture-agnostic branch.

### ISSUE THREAD

**Issue by win10ogod** [arcee-ai/mergekit#445]
When performing passthrough, the model will be severely shrunk. For example, the original model bf16 7GB will have 1G left.

**Comment by win10ogod** [comment]
```
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 3]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
- sources:
  - layer_range: [2, 5]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
- sources:
  - layer_range: [4, 7]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
- sources:
  - layer_range: [6, 9]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
- sources:
  - layer_range: [8, 11]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
- sources:
  - layer_range: [10, 13]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
- sources:
  - layer_range: [12, 15]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
- sources:
  - layer_range: [14, 17]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
- sources:
  - layer_range: [16, 19]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
- sources:
  - layer_range: [18, 21]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
- sources:
  - layer_range: [20, 23]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
- sources:
  - layer_range: [22, 25]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
- sources:
  - layer_range: [24, 27]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
- sources:
  - layer_range: [26, 28]
    model: deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
```
