### ISSUE TITLE
Question about the implement of sign election in TIES

### ISSUE THREAD

**Issue by kobayashikanna01** [arcee-ai/mergekit#474]
Hi,

Thanks for the great contributions! I recently try to reproduce the experiments of TIES, and I find a small part of merged parameters (less than 3%) deviate from my expectation.

Compared to Algorithm 1 in TIES (page 4 in [arxiv](https://arxiv.org/pdf/2306.01708v2)), this toolkit add a `weight` variable for each model. Intuitively, I believe `weight` only affect the step of disjoint merging, which replaces the equation $$\tau_m^p=\frac{1}{\vert A_p\vert}\sum_{t\in A_p}\hat{\tau}^p_t$$ by $\tau_m^p=\frac{1}{\sum_{t\in A_p} w_t}\sum_{t\in A_p}w_t\cdot\hat{\tau}^p_t$ (with $w_1, \cdots, w_n$ representing the `weight` for model 1 to n).

However, I find `weight` does not only affect averaging of retained parameters, but also change the behavior of sign election. Carefully reviewing the codes, I find this toolkit implement TIES based on [Task Arithmetic](https://arxiv.org/abs/2212.04089), which introduces a rescaling variable $\lambda$ (i.e., `weight` here) for all task vectors. 

Following Task Arithmetic, this toolkit multiplies the task vectors by `weight` once after sparsify. It means the magnitude of each parameter is rescaled during sign election. For example, I merge a French model and a Math model with following config:
```
models:
  - model: llama-2-french
    parameters:
      density: 1.0
      weight: 0.2
  - model: llama-2-mathsft
    parameters:
      density: 0.4
      weight: 0.8
merge_method: ties
base_model: llama-2-7b-hf
parameters:
  normalize: true
  int8_mask: true
dtype: float16
```
Then, if this toolkit choose the sign of French model, the original magnitude of a delta parameter in `llama-2-french` should be 4 times larger than the magnitude of corresponding one in `llama-2-mathsft`. 

I am not sure whether it is a correct overriding of TIES. I guess there might be several people hoping the `weight` variables are only active when averaging but do not affect the sign election.
