### ISSUE TITLE
GEmma 3 - pass-merge errors

### ISSUE THREAD

**Issue by David-AU-github** [arcee-ai/mergekit#537]
Updated to latest Mergekit and correct transformers with GEmma 3 ; getting following errors
( simple pass-through merge, same model - no other models )

Model: 12b GEmma 3 it (reg, not "pt" / multimodal version)

NOTE: "mergekit7" is newest install , I have several.

mergekit-yaml --copy-tokenizer --allow-crimes --cuda --out-shard-size 5B --lazy-unpickle --clone-tensors f:/mergefiles/Gemma-3-12B-exp40-3.txt E:/Gemma-3-12B-exp40-3

WARNING:mergekit.merge:Unable to set number of layers for module multi_modal_projector in output config - you may need to manually correct it.
Traceback (most recent call last):
  File "F:\mergekit7\mergekit\mergekit\merge.py", line 300, in _model_out_config
    set_config_value(res, cfg_key, module_layers[module_name])
  File "F:\mergekit7\mergekit\mergekit\common.py", line 37, in set_config_value
    parts = key.split(".")
            ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
Warmup loader cache: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Scripts\mergekit-yaml.exe\__main__.py", line 7, in <module>
  File "C:\Users\david\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\mergekit7\mergekit\mergekit\options.py", line 123, in wrapper
    f(*args, **kwargs)
  File "F:\mergekit7\mergekit\mergekit\scripts\run_yaml.py", line 30, in main
    run_merge(
  File "F:\mergekit7\mergekit\mergekit\merge.py", line 70, in run_merge
    ).plan_to_disk(out_path=out_path)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\mergekit7\mergekit\mergekit\plan.py", line 335, in plan_to_disk
    self._plan()
  File "F:\mergekit7\mergekit\mergekit\plan.py", line 376, in _plan
    self.normalize_config()
  File "F:\mergekit7\mergekit\mergekit\plan.py", line 105, in normalize_config
    raise RuntimeError(
RuntimeError: Model has multiple modules, must use modules: config syntax to work with slices

**Comment by cg123** [comment]
With models like this slicing gets a little bit trickier - since the vision tower and the language model have a different number of layers it doesn't make sense to specify slices in such a way. You can use this new syntax:

```yaml
merge_method: passthrough
modules:
  text_decoder:
    # frankenmerge the text model
    slices:
      - sources:
          - model: google/gemma-3-12b-it
            layer_range: [0, 24]
      - sources:
          - model: google/gemma-3-12b-it
            layer_range: [8, 48]
  vision_tower:
    # keep the vision tower as is
    models:
      - model: google/gemma-3-12b-it
    # or also frankenmerge it?
    # slices:
    #   - sources:
    #       - model: google/gemma-3-12b-it
    #         layer_range: [0, 16]
    #   - sources:
    #       - model: google/gemma-3-12b-it
    #         layer_range: [8, 27]
  multi_modal_projector:
    # no layers in this module just a single set of weights
    models:
      - model: google/gemma-3-12b-it

```
