### ISSUE TITLE
Mapping ChatML Tokens to Native Llama Embeddings in Mergekit

### ISSUE THREAD

**Issue by cyc00518** [arcee-ai/mergekit#540]
Hello,

I am using mergekit to merge multiple models and have encountered a question regarding tokenizer token mapping.

I have three models:

Two of them use native Llama token embeddings (e.g., <|start_header_id|>).
One model is trained in ChatML format (e.g., <|im_start|>).
I want the final merged model to preserve the native Llama token embeddings while allowing inputs in ChatML format to leverage these embeddings. In other words, I want to map the ChatML <|im_start|> token to the native Llama <|start_header_id|> token without overwriting the native tokens from the other models.

I attempted the following configuration:

```
tokenizer:
  source: union
  tokens:
    <|im_start|>:
      source:
        kind: "model_token"
        model: "llama_model"  # Specify the identifier or path of the native Llama model
        token: "<|start_header_id|>"
      force: true
```

However, I'm unsure if this configuration is correct—especially considering that the other two models already use native Llama format. Would this mapping cause any conflicts or unexpected behavior? Is this the recommended approach to ensure the final model retains native Llama embeddings while also utilizing the capabilities learned from the ChatML-formatted model?

Any guidance or recommendations would be greatly appreciated.

Thank you for your assistance!
