### ISSUE TITLE
Nemotron 3.3 attempt.

### ISSUE THREAD

**Issue by Nexesenex** [arcee-ai/mergekit#541]
Hey.

I would like to make a merge of Nemotron 3.1 on a Llama 3.3 instruct base.

From what I understand, Nemotron 3.1 is based on Llama 3.1 instruct.
And Llama 3.1 instruct is based on Llama 3.1 base, like Llama 3.3 instruct is.

So, I wondered if I could substract Llama Instruct 3.1 from Nemotron 3.1, and re-add this the "remaining" Nemotron 3.1 to Llama 3.3 instruct.

I guess it's a task-arithmetic process, so that's what I attempted :

```
merge_method: task_arithmetic
base_model: meta-llama/Llama-3.1-70B-Instruct
models:
  - model: nvidia/Llama-3.1-Nemotron-70B-Instruct-HF
    parameters:
      weight: 1.0
  - model: meta-llama/Llama-3.3-70B-Instruct
    parameters:
      weight: 1.0
dtype: bfloat16
out_dtype: bfloat16
parameters:
  int8_mask: true
  normalize: false
  rescale: true
  filter_wise: false
chat_template: auto
tokenizer:
  source: union
```

It didn't turn into a disaster, the model is coherent, PPL is a bit high (around 4.30 vs around 3.85 for Nemotron 3.1), but I don't even know if I did this correctly accordingly to my objective, or if I just made a watered down mix of both.

Can someone be kind enough to confirm or correct my config file?
