### ISSUE TITLE
Tokenizer & Multimerge Bugs + Miscellaneous Changes

### ISSUE THREAD

**Issue by kromeurus** [arcee-ai/mergekit#548]
Hey, I found a few errors with the latest updates to mergekit plus some noticeable changes that may or may not be bugs. These errors started to show after branch #534 was pushed to main and every version since, they've persisted. 

### Tokenizer

If you try to do a simple passthrough merge to apply a LoRA onto a model, the model will merge but the tokenizer will fail to transfer. See image below. 

![Image](https://github.com/user-attachments/assets/aae98039-1b7b-441b-8bb3-42a93a383416)

Strangely, if you manualy call for the LoRA's tokenizer a source for a seperate merge, it'll work. It seems to be only for a straight LoRA application merges that break. 

### Multimerge

After completing a merge using the !mergekit-multi command, there's a chance that mergekit will try to download all the input models all over again. This bug doesn't happen often, but it's never happened before, so I thought it might be worth at least mentioning. If the error occurs again, I'll post a screenshot of the outputs here. 

### Miscellaneous Changes

Ever since branch #534 was committed, I've noticed that merges take longer to complete than it's previous versions. The time deviation is minimal with smaller merges. However, larger merges are significantly slower. I tried running the same config — one pre, one post commit — and post took roughly double the time even when using --multigpu, yet the resulting merge is the same. I'm not 100% sure what causing it but I did notice the # of it/s is lower post commit then pre. Something is eating up more processing power?

**Comment by kromeurus** [comment]
@cg123 I got the multimerge bug again. Using the latest branch of mergekit and right as the merge finished, it started downloading the models again. 

![Image](https://github.com/user-attachments/assets/0cb3627d-92c7-4256-b204-99e6bd9f64e9)

It eventually stopped when 'there wasn't enough room' but I was looking through the files and couldn't find where it wasn't downloading to. 

![Image](https://github.com/user-attachments/assets/38d4181e-ea03-436d-8388-d3781e19bb78)

Idk why it's doing this now as pre-Gemma3 updates were just fine. There are also issues with SCE recently, a friend made a model and it came out with 3D params, adding ~5B params on top. They ran it again with an older fork and it worked out then.

**Comment by kromeurus** [comment]
Sorry, forgot to mention. This was config.yaml I ran:

```yaml
models:
  - model: kromcomp/L3.1-Nuancev1-12B
    parameters:
      weight: 0.325
      max_iter: 10
      tol: 1e-5
  - model: kromcomp/L3.1-Fragrantv1-12B
    parameters:
      weight: 0.35
      max_iter: 10
      tol: 1e-5
  - model: kromcomp/L3.1-Ransackv1-12B
    parameters:
      weight: 0.325
      max_iter: 10
      tol: 1e-5
base_model: kromcomp/L3.1-Ransackv1-12B
merge_method: karcher
parameters:
  normalize: false
  int8_mask: true
tokenizer:
  source: union
chat_template: llama3
dtype: float32
name: outlaws
```
And this was the command line: `!mergekit-multi config.yaml -I merge --allow-crimes --out-shard-size 3B --gpu-rich --lora-merge-cache loreacache -v --lora-merge-dtype bfloat16 --transformers-cache storage`
