### ISSUE TITLE
Merging language and vision layers

### ISSUE THREAD

**Issue by yukiarimo** [arcee-ai/mergekit#557]
Hi. I saw this:

```
merge_method: dare_ties
base_model: ReadyArt/The-Omega-Directive-Gemma3-12B-v1.0
models:
  - model: ReadyArt/The-Omega-Directive-Gemma3-12B-v1.0
    parameters:
      weight: 0.4
  - model: TheDrummer/Fallen-Gemma3-12B-v1
    parameters:
      weight: 0.3
  - model: allura-org/Gemma-3-Glitter-12B
    parameters:
      weight: 0.3
parameters:
  density: 0.3
tokenizer:
  source: base
chat_template: auto
```

I have a few questions:

1. How to merge specific layers instead of using weights percentages (but provide percents like 30%/70% of how to merge)?
2. How to merge vision parts and language parts of different models?
3. How to know how many layers do I have?
4. How to map used tokens from other models to my custom tokens like: <|im_start|> to <mycustomtoken>?
5. Can somebody please simply explain different between merge methods and which one should I use?

> Note: I'm interested in Gemma 3 12B only!

Thanks!
