### ISSUE TITLE
The epsilon parameter is not working

### ISSUE THREAD

**Issue by Blackstarez** [arcee-ai/mergekit#572]
During della merging, the sparsification function named `della_magprune` **does not correctly receive the epsilon argument**. 

Just before calling the sparsification function, the task vector is extracted using the `get_task_vector` function in _generalized_task_arithmetic.py around line 118._ 

After that, **_epsilon_** or **_gamma_** is supposed to be extracted based on the returned value **_tvs_** _between lines 129 and 135_, but these variables are not stored in **_tvs_**. 

I would like to know how to properly specify epsilon or gamma. 

I have attached the config.yml file for reference.

``` yml
models:
  - model: ./model_a
    parameters:
      weight: 1.0
  - model: ./model_b
    parameters:
      weight: 1.0
merge_method: della
base_model: microsoft/phi-2
parameters:
  density: 0.8
  epsilon: 0.3
  normalize: true
dtype: float16
```
